package:
  name: modrev
  version: "1.3.1"

source:
  url: https://lourencomatos.com/ModRev1.3.1/modrev
  sha256: e791a4e6b666d5a92eb3a4dac428f35db733097f50fa9727b3d7e6aa5f810b93

build:
  number: 0

requirements:
  run:
    - libgcc-ng

about:
  home:  https://filipegouveia.github.io/ModRev/
