package:
  name: modrev
  version: "1.3.1"

source:
  url: https://filipegouveia.github.io/ModRev/ModRev-1.3.1.zip

build:
  number: 0
  script:
    - cd src
    - make
    
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx')}}
    - boost
    - make
  run:
    - libgcc-ng

about:
  home:  https://filipegouveia.github.io/ModRev/
